### ISSUE TITLE
npm install ERROR

### ISSUE THREAD

**Issue by VsCodeProjects** [Votion-Development/Dashactyl#14]
![image](https://user-images.githubusercontent.com/89304431/146080016-fce07471-d7b1-42f1-ab46-0111f952aa7f.png)
When I do npm install for all the packages to install I get an error. How do I fix this.

**Comment by VsCodeProjects** [comment]
oh ok I will try that

**Comment by VsCodeProjects** [comment]
![image](https://user-images.githubusercontent.com/89304431/146081691-edde1173-532d-4616-b977-4d89c2d10718.png)
What should i do for that I tried everything

**Comment by Dviih** [comment]
> ![image](https://user-images.githubusercontent.com/89304431/146081691-edde1173-532d-4616-b977-4d89c2d10718.png) What should i do for that I tried everything

You need to rename settings-template.yml to settings.yml and then configure (Probably you gave up or you find the solution in discord)
