### ISSUE TITLE
"The provided location ID must be a string." 

### ISSUE THREAD

**Issue by KiraZ-69** [Votion-Development/Dashactyl#26]
Hello on my Dashactyl panel
when I want to create a server I get an error: "The provided location ID must be a string."

you will find attached my config and a screen of the location of my pterodactyl panel
![image](https://user-images.githubusercontent.com/88207784/152889123-09ea5fee-cfc2-4a97-a14a-e10a4582b1ed.png)
![image](https://user-images.githubusercontent.com/88207784/152889165-71bb6ef9-8bbb-4c19-9a00-52ef457f9c6e.png)

**Comment by JamieGrimwood** [comment]
Hello, please follow the documentation. https://docs.votion.dev
