### ISSUE TITLE
Afk page not working

### ISSUE THREAD

**Issue by acktarcodes** [Votion-Development/Dashactyl#34]
So i've recently installed dashactyl but my afk page is not working for some reason. Has anyone come across this issue and knows how to fix it?

I've ensured that:
- there is no ad blockers enabled on my browser
- no other afk pages is opened at the same time

But it keeps going into an endless loop of the following message:

```An error has occured and you have been disconnected from the AFK page.

To resolve this error, you must reload the page.

Error: An unexpected error has occured that resulted in the AFK page crashing.```

**Comment by babyharpsea** [comment]
Hello, could you please provide console logs?

**Comment by acktarcodes** [comment]
Hey so i've played with it a bit and got it to work on localhost. however when i upload it to a server, i get the above issue.

Unfortunately there is no error messages on console

> Hello, could you please provide console logs?

**Comment by acktarcodes** [comment]
```widget.min.js:1 WebSocket connection to 'wss://tkr.arc.io/announce' failed: 
y @ widget.min.js:1
core.js?44095ae:32 
Uncaught Error: connection error to wss://tkr.arc.io/announce
    at WebSocket._ws.onerror (core.js?44095ae:15:1541)
vendors~widget-sc-client.js?35fccb86:1 WebSocket connection to 'wss://socket.arc.io/socketcluster/?nodeId=HXdhbinZm6sfYwfE4g59Gi' failed: 
i @ vendors~widget-sc-client.js?35fccb86:1
afk:38 WebSocket connection to 'wss://en.serverkur.net/earn/afk' failed: 
(anonymous) @ afk:38
vendors~widget-sc-client.js?35fccb86:1 WebSocket connection to 'wss://socket.arc.io/socketcluster/?nodeId=HXdhbinZm6sfYwfE4g59Gi' failed:```

This is what pops in the browser console

**Comment by acktarcodes** [comment]
```Uncaught Error: connection error to wss://tkr.arc.io/announce
    at WebSocket._ws.onerror (core.js?44095ae:15:1541)

WebSocket connection to 'wss://en.serverkur.net/earn/afk' failed: 
(anonymous) @ afk:38

vendors~widget-sc-client.js?35fccb86:1 WebSocket connection to 'wss://socket.arc.io/socketcluster/?nodeId=HXdhbinZm6sfYwfE4g59Gi' failed:```

What could be the reasons for this and how could i potentially fix it

**Comment by acktarcodes** [comment]
I am using Nginx to proxy the website. Do i need to add something to my config to allow the websocket connection?

**Comment by acktarcodes** [comment]
![Screenshot (57)](https://user-images.githubusercontent.com/103925997/164167975-5c73b2a6-a988-4768-af4b-0a8870e75521.png)

![Screenshot (58)](https://user-images.githubusercontent.com/103925997/164168728-cc225733-6246-46d7-89a6-39c78238c9f2.png)

Can it be an nginx misconfiguration? Thats the only reason i see for it to not work on the server since its working on localhost.

**Comment by acktarcodes** [comment]
Fixed. it was an nginx misconfiguration :) for some reason it didnt work with the one provided in the doc

**Comment by blazecoding2009** [comment]
Hey @acktarcodes 
Do you mind sharing with us what you changed in the nginx configuration?

Thanks and regards,
Blaze
