### ISSUE TITLE
Discord redirect loop 

### ISSUE THREAD

**Issue by ThePolishLemon** [Votion-Development/Dashactyl#36]
Hi I am encountering an issue with your dashboard, i get constantly redirected to the same place when logging in with discord 

Video: https://cdn.discordapp.com/attachments/828634562863038544/982003582167568465/2022-06-02_21-31-01.mp4

**Comment by ThePolishLemon** [comment]
also, I downloaded it from the source code as I saw it had a discord OAuth fix so its not the issue

**Comment by blazecoding2009** [comment]
If you’re caught in a login loop with Discord OAuth2 make sure to follow these steps:
• update your Pterodactyl credentials in settings.yml
• set "secure" to false in settings.yml
• restart Dashactyl
