### ISSUE TITLE
getting connect uri error

### ISSUE THREAD

**Issue by ErrorDoc404** [Votion-Development/Dashactyl#39]
![image](https://user-images.githubusercontent.com/35562217/187041756-bed790d7-fd7c-4ff3-b317-5e5d2d2b0116.png)

**Comment by ErrorDoc404** [comment]
i am using 
mongodb+srv://<user>:<password>@cluster0.hmj7hpt.mongodb.net

**Comment by BeastGamer81** [comment]
Go to Atlas and use Driver Version V2.12 or smth and it will work
